#!/bin/bash
APP_DIR="/lib/mouse-piper"

# Get the absolute path of the directory containing this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "$SCRIPT_DIR"

# Path to the file you want to check
TARGET_FILE="$SCRIPT_DIR/mouse-piper.py"

# Check if it exists
if [ ! -f "$TARGET_FILE" ]; then
    cd "$APP_DIR" || /bin/true
    exec python3 "$APP_DIR/mouse-piper.py" "$@"
else
  exec python3 ./mouse-piper.py "$@"
fi